Repository digitallinguistics/data-explorer, pull requests merged in 2022-03, with the labels that each got.

#121 add PR template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: 📃 documentation

#123 update readme and year test
  .github/workflows/deploy.yml
  README.md
  test/docs.unit.js
Labels: 📃 documentation

#122 add issue templates
  .github/CONTRIBUTING.md
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  middleware/locals.js
Labels: 📃 documentation

#127 Cypress
  .eslintrc.yml
  .github/CONTRIBUTING.md
  app/index.js
  package-lock.json
  package.json
  pages/404/404.test.js
  pages/Home/Home.test.js
  pages/Languages/Languages.test.js
  pages/index.test.js
  test/cypress.json
Labels: ⚒️ development

#130 Add static routing
  app/index.js
  app/routes.js
  assets/images/oxalis-1280x640.png
  assets/images/oxalis-BW.png
  assets/images/oxalis-BW.svg
  assets/images/oxalis.png
  assets/images/oxalis.svg
  pages/index.js
Labels: 💻 site

#128 set up helmet
  app/index.js
  middleware/helmet.js
  package-lock.json
  package.json
Labels: 🔒 security

#138 About page
  app/routes.js
  layout/nav.hbs
  layout/navbar.hbs
  pages/About/About.hbs
  pages/About/About.js
  pages/index.js
Labels: 💻 site

#132 install design system and set up build process
  app/index.js
  assets/images/octicon.black.svg
  build/copyAssets.js
  build/index.js
  package-lock.json
  package.json
Labels: ⚒️ development

#139 add Projects page
  app/routes.js
  layout/navbar.hbs
  pages/Projects/Projects.hbs
  pages/Projects/Projects.js
  pages/index.js
Labels: 💻 site

#140 Add a dictionaries page
  app/routes.js
  layout/navbar.hbs
  pages/Dictionaries/Dictionaries.hbs
  pages/Dictionaries/Dictionaries.js
  pages/index.js
Labels: 💻 site

#129 Add footer to the site
  layout/footer.hbs
  layout/index.hbs
Labels: 💻 site, 🎁 feature

#144 login / logout
  app/auth.js
  app/index.js
  app/locals.js
  app/routes.js
  config/app.js
  constants/index.js
  layout/help-nav.hbs
  layout/main-nav.hbs
  layout/navbar.hbs
  layout/user.hbs
  middleware/auth.js
  middleware/locals.js
  middleware/logger.js
  package-lock.json
  package.json
  pages/500/500.js
  pages/index.test.js
Labels: 💻 site, 🎁 feature, 🔒 security

#146 Zenodo
  CITATION.cff
  README.md
Labels: 📃 documentation

#147 favicon
  assets/favicon.ico
  assets/images/favicon.svg
  layout/head.hbs
Labels: 💻 site, 🎁 feature

#148 inline critical CSS
  .eslintrc.yml
  .gitignore
  app/locals.js
  build/buildCSS.js
  build/index.js
  layout/head.hbs
  middleware/locals.js
  package-lock.json
Labels: ⚒️ development, 💻 site, ⏩ performance

#152 CSS reset
  build/buildCSS.js
  build/convertLESS.js
  layout/layout.less
  package-lock.json
  package.json
Labels: ⚒️ development, 💻 site, 🎁 feature

#151 add welcome note
  pages/Home/Home.hbs
  pages/Home/Home.test.js
  pages/index.test.js
Labels: 🎁 feature, Home

#153 host fonts
  assets/fonts/Fira/FiraMono-Bold.woff2
  assets/fonts/Fira/FiraMono-Medium.woff2
  assets/fonts/Fira/FiraMono-Regular.woff2
  assets/fonts/Fira/FiraSans-Bold.woff2
  assets/fonts/Fira/FiraSans-BoldItalic.woff2
  assets/fonts/Fira/FiraSans-Book.woff2
  assets/fonts/Fira/FiraSans-BookItalic.woff2
  assets/fonts/Fira/FiraSans-Eight.woff2
  assets/fonts/Fira/FiraSans-EightItalic.woff2
  assets/fonts/Fira/FiraSans-ExtraBold.woff2
  assets/fonts/Fira/FiraSans-ExtraBoldItalic.woff2
  assets/fonts/Fira/FiraSans-ExtraLight.woff2
  assets/fonts/Fira/FiraSans-ExtraLightItalic.woff2
  assets/fonts/Fira/FiraSans-Four.woff2
  assets/fonts/Fira/FiraSans-FourItalic.woff2
  assets/fonts/Fira/FiraSans-Hair.woff2
  assets/fonts/Fira/FiraSans-HairItalic.woff2
  assets/fonts/Fira/FiraSans-Heavy.woff2
  assets/fonts/Fira/FiraSans-HeavyItalic.woff2
  assets/fonts/Fira/FiraSans-Italic.woff2
  assets/fonts/Fira/FiraSans-Light.woff2
  assets/fonts/Fira/FiraSans-LightItalic.woff2
  assets/fonts/Fira/FiraSans-Medium.woff2
  assets/fonts/Fira/FiraSans-MediumItalic.woff2
  assets/fonts/Fira/FiraSans-Regular.woff2
  assets/fonts/Fira/FiraSans-SemiBold.woff2
  assets/fonts/Fira/FiraSans-SemiBoldItalic.woff2
  assets/fonts/Fira/FiraSans-Thin.woff2
  assets/fonts/Fira/FiraSans-ThinItalic.woff2
  assets/fonts/Fira/FiraSans-Two.woff2
  assets/fonts/Fira/FiraSans-TwoItalic.woff2
  assets/fonts/Fira/FiraSans-Ultra.woff2
  assets/fonts/Fira/FiraSans-UltraItalic.woff2
  assets/fonts/Fira/FiraSans-UltraLight.woff2
  assets/fonts/Fira/FiraSans-UltraLightItalic.woff2
  assets/fonts/Libertinus/LibertinusKeyboard-Regular.woff2
  assets/fonts/Libertinus/LibertinusMath-Regular.woff2
  assets/fonts/Libertinus/LibertinusMono-Regular.woff2
  assets/fonts/Libertinus/LibertinusSans-Bold.woff2
  assets/fonts/Libertinus/LibertinusSans-Italic.woff2
  assets/fonts/Libertinus/LibertinusSans-Regular.woff2
  assets/fonts/Libertinus/LibertinusSerif-Bold.woff2
  assets/fonts/Libertinus/LibertinusSerif-BoldItalic.woff2
  assets/fonts/Libertinus/LibertinusSerif-Italic.woff2
  assets/fonts/Libertinus/LibertinusSerif-Regular.woff2
  assets/fonts/Libertinus/LibertinusSerif-Semibold.woff2
  assets/fonts/Libertinus/LibertinusSerif-SemiboldItalic.woff2
  assets/fonts/Libertinus/LibertinusSerifDisplay-Regular.woff2
  assets/fonts/Libertinus/LibertinusSerifInitials-Regular.woff2
  build/copyAssets.js
  package-lock.json
  package.json
Labels: ⚒️ development

#154 preload critical assets
  layout/head.hbs
Labels: 💻 site, ⏩ performance

#157 add release info
  .github/CONTRIBUTING.md
Labels: 📃 documentation

#156 handle uncaught exceptions
  app/errors.js
  app/index.js
Labels: ✨ enhancement

#159 use Fira Sans for site font
  app/locals.js
  assets/fonts/FiraMono-Bold.woff2
  assets/fonts/FiraMono-Medium.woff2
  assets/fonts/FiraMono-Regular.woff2
  assets/fonts/FiraSans-Bold.woff2
  assets/fonts/FiraSans-BoldItalic.woff2
  assets/fonts/FiraSans-Book.woff2
  assets/fonts/FiraSans-BookItalic.woff2
  assets/fonts/FiraSans-Eight.woff2
  assets/fonts/FiraSans-EightItalic.woff2
  assets/fonts/FiraSans-ExtraBold.woff2
  assets/fonts/FiraSans-ExtraBoldItalic.woff2
  assets/fonts/FiraSans-ExtraLight.woff2
  assets/fonts/FiraSans-ExtraLightItalic.woff2
  assets/fonts/FiraSans-Four.woff2
  assets/fonts/FiraSans-FourItalic.woff2
  assets/fonts/FiraSans-Hair.woff2
  assets/fonts/FiraSans-HairItalic.woff2
  assets/fonts/FiraSans-Heavy.woff2
  assets/fonts/FiraSans-HeavyItalic.woff2
  assets/fonts/FiraSans-Italic.woff2
  assets/fonts/FiraSans-Light.woff2
  assets/fonts/FiraSans-LightItalic.woff2
  assets/fonts/FiraSans-Medium.woff2
  assets/fonts/FiraSans-MediumItalic.woff2
  assets/fonts/FiraSans-Regular.woff2
  assets/fonts/FiraSans-SemiBold.woff2
  assets/fonts/FiraSans-SemiBoldItalic.woff2
  assets/fonts/FiraSans-Thin.woff2
  assets/fonts/FiraSans-ThinItalic.woff2
  assets/fonts/FiraSans-Two.woff2
  assets/fonts/FiraSans-TwoItalic.woff2
  assets/fonts/FiraSans-Ultra.woff2
  assets/fonts/FiraSans-UltraItalic.woff2
  assets/fonts/FiraSans-UltraLight.woff2
  assets/fonts/FiraSans-UltraLightItalic.woff2
  assets/fonts/LibertinusKeyboard-Regular.woff2
  assets/fonts/LibertinusMath-Regular.woff2
  assets/fonts/LibertinusMono-Regular.woff2
  assets/fonts/LibertinusSans-Bold.woff2
  assets/fonts/LibertinusSans-Italic.woff2
  assets/fonts/LibertinusSans-Regular.woff2
  assets/fonts/LibertinusSerif-Bold.woff2
  assets/fonts/LibertinusSerif-BoldItalic.woff2
  assets/fonts/LibertinusSerif-Italic.woff2
  assets/fonts/LibertinusSerif-Regular.woff2
  assets/fonts/LibertinusSerif-Semibold.woff2
  assets/fonts/LibertinusSerif-SemiboldItalic.woff2
  assets/fonts/LibertinusSerifDisplay-Regular.woff2
  assets/fonts/LibertinusSerifInitials-Regular.woff2
  build/buildCSS.js
  layout/footer.hbs
  layout/index.less
  package-lock.json
  package.json
Labels: 🎁 feature, About

#160 main layout styling
  build/convertLESS.js
  layout/footer.hbs
  layout/head.hbs
  layout/index.less
  package-lock.json
  pages/404/404.hbs
  pages/500/500.hbs
  pages/About/About.hbs
  pages/Dictionaries/Dictionaries.hbs
  pages/Home/Home.hbs
  pages/Languages/Languages.hbs
  pages/Projects/Projects.hbs
Labels: 💻 site, 🎁 feature

#163 SVG sprites
  app/locals.js
  assets/images/octicon.svg
  assets/images/oxalis-BW.png
  assets/images/oxalis-color.svg
  assets/images/oxalis.png
  assets/images/social.png
  build/buildCSS.js
  build/buildSVG.js
  build/copyAssets.js
  build/index.js
  layout/footer.hbs
  layout/head.hbs
  layout/index.hbs
  layout/layout.less
  layout/sprites.hbs
  layout/style.hbs
  package-lock.json
  package.json
Labels: ⚒️ development, ⏩ performance

#164 change to black & white favicon
  assets/images/favicon.svg
Labels: 💻 site, 🎁 feature

#165 footer styling
  .github/CONTRIBUTING.md
  layout/footer.hbs
  layout/footer.less
  layout/index.less
  layout/style.hbs
Labels: 💻 site, 🎁 feature

#169 Update citation
  .gitignore
  CITATION.cff
  build/updateCitation.js
  layout/footer.hbs
  layout/style.hbs
  package.json
Labels: ⚒️ development, 📃 documentation

#171 footer background
  build/copyAssets.js
  layout/footer.hbs
  layout/footer.less
Labels: 💻 site, 🎁 feature

#172 footer links
  layout/footer.hbs
  layout/footer.less
  package-lock.json
  package.json
Labels: 💻 site, 🐞 bug

#176 navbar styling
  assets/images/alert-circle.svg
  assets/images/help-circle.svg
  assets/images/info-circle.svg
  assets/images/megaphone.svg
  assets/images/menu.svg
  assets/images/plus-circle.svg
  layout/footer.hbs
  layout/footer.less
  layout/help-nav.hbs
  layout/help-nav.less
  layout/index.less
  layout/main-nav.hbs
  layout/main-nav.less
  layout/nav-link.less
  layout/navbar.hbs
  layout/navbar.less
  layout/user.hbs
  layout/user.less
Labels: 💻 site, 🎁 feature

#177 design@0.6.0
  package-lock.json
  package.json
Labels: 💻 site

#178 add site logo to nav
  assets/images/oxalis-white.svg
  layout/navbar.hbs
  layout/navbar.less
Labels: 💻 site, 🎁 feature

#180 add footer styles for small screens
  layout/footer.hbs
  layout/footer.less
Labels: 💻 site, 🐞 bug

#181 update dependencies
  package-lock.json
  package.json
Labels: ⚒️ development

#182 add simple test database
  .github/CONTRIBUTING.md
  config/database.js
  data/languages.yml
  package.json
  services/Database.js
  services/Database.unit.js
Labels: ⚒️ development

#192 Add tests for pages without them
  pages/index.test.js
Labels: ⚒️ development
